version: '3'

services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile.app
    tty: true
    command: npm start
    environment:
      - NODE_ENV
      - NODE_PORT
      - NODE_SESSION_COOKIE
      - NODE_COOKIE_SECRET
      - MONGO_PORT
      - MONGO_DB
      - STRIPE_PUBLIC_KEY
      - STRIPE_PRIVATE_KEY
      - STRIPE_HOOK_PATH
      - STRIPE_HOOK_SECRET
      - STRIPE_PRICE_ID
      - APP_HOST
      - MAIL_ADDRESS
    volumes:
      - ./src:/app/src
      - static-assets:/app/build/client
    depends_on:
      - mongo

  mailer:
    build:
      context: .
      dockerfile: ./Dockerfile.mailer
    command: node src/mailer/mailer.js
    environment:
      - MONGO_PORT
      - MONGO_DB
      - MAIL_SMTP_PORT
      - MAIL_USER
      - MAIL_PASSWORD
      - MAIL_ADDRESS
    volumes:
      - ./src/mailer:/app/src/mailer
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    command: --quiet --logpath /dev/null
    volumes:
      - ./data/mongo:/data/db

  nginx:
    image: nginx:alpine
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
      - NODE_PORT
    volumes:
      - ./config/nginx.conf:/etc/nginx/templates/default.conf.template
      - static-assets:/app/public
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  static-assets:
