version: '3'
services:

  app:
    build: .
    environment:
      - NODE_ENV
      - NODE_PORT
      - NODE_SESSION_COOKIE
      - NODE_COOKIE_SECRET
      - MONGO_PORT
      - MONGO_DB
      - SERVERNAME
    volumes:
      - ./server:/app/server
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ./data/db:/data/db

  nginx:
    image: nginx:1.19
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
      - NODE_PORT
      - SERVERNAME
    volumes:
      - ./config/nginx.conf:/etc/nginx/templates/default.conf.template
      - ./client:/app/client
    ports:
      - 80:80
    depends_on:
      - app
