version: '3'

services:

  app:
    environment:
      - NODE_ENV=production

  prometheus:
    image: prom/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    depends_on:
      - app

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - prometheus