version: '3'

services:

  app:
    environment:
      - NODE_ENV=testing
      - MONGO_DB=${MONGO_DB}-test

  cypress:
    build:
      context: .
      dockerfile: ./Dockerfile.tests
    command: npx cypress run --browser chrome
    environment:
      - CYPRESS_BASE_URL=http://app:${NODE_PORT}
      - CYPRESS_MONGO_PORT=${MONGO_PORT}
      - CYPRESS_MONGO_DB=${MONGO_DB}-test
    volumes:
      - ./config/cypress.json:/app/cypress.json
      - ./src:/app/src
    depends_on:
      - app