version: '3'

services:

  app:
    build: .
    tty: true
    environment:
      - NODE_ENV
      - NODE_PORT
      - NODE_SESSION_COOKIE
      - NODE_COOKIE_SECRET
      - MONGO_PORT
      - MONGO_DB
      - STRIPE_PUBLIC_KEY
      - STRIPE_PRIVATE_KEY
      - STRIPE_HOOK_SECRET
      - STRIPE_SUBSCRIPTION_ID
      - SERVERNAME
    volumes:
      - ./src:/app/src
      - static-assets:/app/build/client
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    command: --quiet
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ./data/mongo:/data/db

  nginx:
    image: nginx:alpine
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
      - NODE_PORT
      - SERVERNAME
    volumes:
      - ./config/nginx.conf:/etc/nginx/templates/default.conf.template
      - static-assets:/app/public
    ports:
      - 80:80
    depends_on:
      - app

  prometheus:
    image: prom/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--log.level=warn"
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    depends_on:
      - app

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  static-assets:
