version: '3'

services:

  app:
    environment:
      - NODE_ENV=development

  mailer:
    command: npx nodemon --watch src/mailer src/mailer/mailer.mjs

  mailhog:
    build:
      context: .
      dockerfile: ./Dockerfile.mailhog
    ports:
      - 8025:8025

  mongo:
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

  stripe-cli:
    image: stripe/stripe-cli
    command: listen --forward-to app:${NODE_PORT}/${STRIPE_HOOK_PATH}
    environment:
      - STRIPE_API_KEY=${STRIPE_PRIVATE_KEY}
      - STRIPE_DEVICE_NAME=docker
    depends_on:
      - app
